# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Users\framo\Desktop\ProgettoING-master\form_ui\Accesso_Cuoco.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql
from MySQLdb import Error
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QDialog, QPushButton
from .Lista_comande import Ui_formListaComande
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QMessageBox
from db_connection import get_connection


class Ui_Form_Accesso_Cuoco(object):
    FormAccessoCuoco=None
    def setupUi(self, Form_Accesso_Cuoco):
        self.FormAccessoCuoco=Form_Accesso_Cuoco
        Form_Accesso_Cuoco.setObjectName("Form_Accesso_Cuoco")
        Form_Accesso_Cuoco.resize(780, 613)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form_Accesso_Cuoco.setFont(font)
        Form_Accesso_Cuoco.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.line = QtWidgets.QFrame(Form_Accesso_Cuoco)
        self.line.setGeometry(QtCore.QRect(0, 40, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form_Accesso_Cuoco)
        self.line_2.setGeometry(QtCore.QRect(0, 560, 791, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelAccessoCuoco = QtWidgets.QLabel(Form_Accesso_Cuoco)
        self.labelAccessoCuoco.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelAccessoCuoco.setFont(font)
        self.labelAccessoCuoco.setObjectName("labelAccessoCuoco")
        self.lblDataEOra = QtWidgets.QLabel(Form_Accesso_Cuoco)
        self.lblDataEOra.setGeometry(QtCore.QRect(580, 70, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblDataEOra.setFont(font)
        self.lblDataEOra.setObjectName("lblDataEOra")
        self.btListaComande = QtWidgets.QPushButton(Form_Accesso_Cuoco)
        self.btListaComande.setGeometry(QtCore.QRect(20, 140, 744, 371))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btListaComande.setFont(font)
        self.btListaComande.setStyleSheet("\n"
"\n"
"background-color: rgb(245, 243, 201);")
        self.btListaComande.setObjectName("btListaComande")
        self.label = QtWidgets.QLabel(Form_Accesso_Cuoco)
        self.label.setGeometry(QtCore.QRect(170, 580, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_Accesso_Cuoco)
        self.label_2.setGeometry(QtCore.QRect(0, 580, 41, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("F:\\Users\\framo\\Desktop\\ProgettoING-master\\form_ui\\../../../Downloads/png-transparent-back-entrance-exit-logout-quit-commonmat-icon-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form_Accesso_Cuoco)
        self.btListaComande.clicked.connect(self.btListaComandeClicked)
        QtCore.QMetaObject.connectSlotsByName(Form_Accesso_Cuoco)

    def retranslateUi(self, Form_Accesso_Cuoco):
        _translate = QtCore.QCoreApplication.translate
        Form_Accesso_Cuoco.setWindowTitle(_translate("Form_Accesso_Cuoco", "Accesso Cuoco"))
        self.labelAccessoCuoco.setText(_translate("Form_Accesso_Cuoco", "Accesso: Cuoco"))
        self.lblDataEOra.setText(_translate("Form_Accesso_Cuoco", "Mercoledì 06/03/2024"))
        self.btListaComande.setText(_translate("Form_Accesso_Cuoco", "Lista Comande"))

    def btListaComandeClicked(self):
        # Blocca la finestra corrente
        self.FormAccessoCuoco.setEnabled(False)


        # Crea un'istanza della seconda form e aprila
        self.listaComande_form = QDialog()
        self.ui_lista_comande = Ui_formListaComande()
        self.ui_lista_comande.setupUi(self.listaComande_form)
        self.listaComande_form.exec_()

        # Riattiva la finestra corrente dopo che la seconda form viene chiusa
        self.FormAccessoCuoco.setEnabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Accesso_Cuoco = QtWidgets.QDialog()
    ui = Ui_Form_Accesso_Cuoco()
    ui.setupUi(Form_Accesso_Cuoco)
    Form_Accesso_Cuoco.show()
    sys.exit(app.exec_())
