# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formAggiungiModificaNomeElemento.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formCU_elementoMagazzino(object):
    def setupUi(self, formCU_elementoMagazzino):
        formCU_elementoMagazzino.setObjectName("formCU_elementoMagazzino")
        formCU_elementoMagazzino.resize(320, 268)
        formCU_elementoMagazzino.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.label = QtWidgets.QLabel(formCU_elementoMagazzino)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formCU_elementoMagazzino)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(formCU_elementoMagazzino)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(formCU_elementoMagazzino)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btEsegui = QtWidgets.QPushButton(formCU_elementoMagazzino)
        self.btEsegui.setGeometry(QtCore.QRect(10, 210, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.btEsegui.setFont(font)
        self.btEsegui.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btEsegui.setObjectName("btEsegui")
        self.txtNome = QtWidgets.QLineEdit(formCU_elementoMagazzino)
        self.txtNome.setGeometry(QtCore.QRect(140, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.txtNome.setFont(font)
        self.txtNome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtNome.setText("")
        self.txtNome.setObjectName("txtNome")
        self.txtIntolleranze = QtWidgets.QTextEdit(formCU_elementoMagazzino)
        self.txtIntolleranze.setGeometry(QtCore.QRect(140, 50, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.txtIntolleranze.setFont(font)
        self.txtIntolleranze.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtIntolleranze.setObjectName("txtIntolleranze")
        self.checkBoxPiccante = QtWidgets.QCheckBox(formCU_elementoMagazzino)
        self.checkBoxPiccante.setGeometry(QtCore.QRect(140, 142, 16, 21))
        self.checkBoxPiccante.setText("")
        self.checkBoxPiccante.setObjectName("checkBoxPiccante")
        self.checkBoxVegabo = QtWidgets.QCheckBox(formCU_elementoMagazzino)
        self.checkBoxVegabo.setGeometry(QtCore.QRect(140, 177, 20, 20))
        self.checkBoxVegabo.setText("")
        self.checkBoxVegabo.setObjectName("checkBoxVegabo")

        self.retranslateUi(formCU_elementoMagazzino)
        QtCore.QMetaObject.connectSlotsByName(formCU_elementoMagazzino)

    def retranslateUi(self, formCU_elementoMagazzino):
        _translate = QtCore.QCoreApplication.translate
        formCU_elementoMagazzino.setWindowTitle(_translate("formCU_elementoMagazzino", "Dialog"))
        self.label.setText(_translate("formCU_elementoMagazzino", "Nome:"))
        self.label_2.setText(_translate("formCU_elementoMagazzino", "Intolleranze:"))
        self.label_4.setText(_translate("formCU_elementoMagazzino", "Piccante:"))
        self.label_5.setText(_translate("formCU_elementoMagazzino", "Vegano:"))
        self.btEsegui.setText(_translate("formCU_elementoMagazzino", "Esegui operazione"))
import icons_rc
