# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formAggiungiModificaNomeElemento.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import classi.GestoriDB.GestoreElementiMagazzino as GestoreDBMagazzino


class Ui_formCU_nomeElemento(object):
    def setupUi(self, formCU_nomeElemento):
        self.idToUpdate = -1
        self.fCU_nomeElemento = formCU_nomeElemento
        formCU_nomeElemento.setObjectName("formCU_nomeElemento")
        formCU_nomeElemento.resize(320, 268)
        formCU_nomeElemento.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.label = QtWidgets.QLabel(formCU_nomeElemento)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formCU_nomeElemento)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(formCU_nomeElemento)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(formCU_nomeElemento)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btEsegui = QtWidgets.QPushButton(formCU_nomeElemento)
        self.btEsegui.setGeometry(QtCore.QRect(10, 210, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.btEsegui.setFont(font)
        self.btEsegui.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btEsegui.setObjectName("btEsegui")
        self.txtNome = QtWidgets.QLineEdit(formCU_nomeElemento)
        self.txtNome.setGeometry(QtCore.QRect(140, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.txtNome.setFont(font)
        self.txtNome.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtNome.setText("")
        self.txtNome.setObjectName("txtNome")
        self.txtIntolleranze = QtWidgets.QTextEdit(formCU_nomeElemento)
        self.txtIntolleranze.setGeometry(QtCore.QRect(140, 50, 171, 81))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        self.txtIntolleranze.setFont(font)
        self.txtIntolleranze.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtIntolleranze.setObjectName("txtIntolleranze")
        self.checkBoxPiccante = QtWidgets.QCheckBox(formCU_nomeElemento)
        self.checkBoxPiccante.setGeometry(QtCore.QRect(140, 142, 16, 21))
        self.checkBoxPiccante.setText("")
        self.checkBoxPiccante.setObjectName("checkBoxPiccante")
        self.checkBoxVegano = QtWidgets.QCheckBox(formCU_nomeElemento)
        self.checkBoxVegano.setGeometry(QtCore.QRect(140, 177, 20, 20))
        self.checkBoxVegano.setText("")
        self.checkBoxVegano.setObjectName("checkBoxVegano")
        self.btEsegui.clicked.connect(self.btEseguiClicked)
        self.retranslateUi(formCU_nomeElemento)
        QtCore.QMetaObject.connectSlotsByName(formCU_nomeElemento)

    def retranslateUi(self, formCU_nomeElemento):
        _translate = QtCore.QCoreApplication.translate
        if self.idToUpdate == -1:
            formCU_nomeElemento.setWindowTitle(_translate("formCU_nomeElemento", "Inserisci nomeElemento"))
        else:
            formCU_nomeElemento.setWindowTitle(_translate("formCU_nomeElemento", "Modifica nomeElemento"))
        self.label.setText(_translate("formCU_nomeElemento", "Nome:"))
        self.label_2.setText(_translate("formCU_nomeElemento", "Intolleranze:"))
        self.label_4.setText(_translate("formCU_nomeElemento", "Piccante:"))
        self.label_5.setText(_translate("formCU_nomeElemento", "Vegano:"))
        self.btEsegui.setText(_translate("formCU_nomeElemento", "Esegui operazione"))

    def btEseguiClicked(self):
        dlg = QMessageBox()
        dlg.setWindowTitle("Conferma")
        dlg.setText("Sei sicuro di voler proseguire?")
        dlg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        dlg.setIcon(QMessageBox.Warning)
        button = dlg.exec()
        if button == QMessageBox.Yes:
            if self.idToUpdate == -1:
                nome = self.txtNome.text()
                piccante = self.checkBoxPiccante.isChecked()
                vegano = self.checkBoxVegano.isChecked()
                intolleranze = self.txtIntolleranze.text()
                query = f"insert into nomeElemento(nome, piccante, vegano, intolleranze) VALUES ('{nome}', {piccante}, {vegano}, '{intolleranze}')"
                GestoreDBMagazzino.eseguiQuery()
                self.fCU_nomeElemento.close()
            else:
                nome = self.txtNome.text()
                piccante = self.checkBoxPiccante.isChecked()
                vegano = self.checkBoxVegano.isChecked()
                intolleranze = self.txtIntolleranze.text()
                query = f"UPDATE nomeElemento SET nome = '{nome}', piccante = {piccante}, vegano = {vegano}, intolleranze = '{intolleranze}' WHERE id = {self.idToUpdate}"
                GestoreDBMagazzino.eseguiQuery()
                self.fCU_nomeElemento.close()
        # TODO check per evitare di inserire valori nulli
