# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestioneNomi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql
import mysql.connector
from PyQt5.QtSql import QSqlQueryModel
from PyQt5.QtWidgets import QTableWidgetItem, QMainWindow, QPushButton, QMessageBox
import Resources.icons


class Ui_Dialog(object):
    def chiudiMain(self):
        pass

    def setupUi(self, Dialog, Parent):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 540)
        Dialog.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.tableNomi = QtWidgets.QTableWidget(Dialog)
        self.tableNomi.setGeometry(QtCore.QRect(10, 10, 501, 361))
        self.tableNomi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableNomi.setObjectName("tableNomi")
        self.tableNomi.setColumnCount(5)
        self.tableNomi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(4, item)
        self.btInserisciNome = QtWidgets.QPushButton(Dialog)
        self.btInserisciNome.setGeometry(QtCore.QRect(10, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btInserisciNome.setFont(font)
        self.btInserisciNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btInserisciNome.setObjectName("btInserisciNome")
        self.btModificaNome = QtWidgets.QPushButton(Dialog)
        self.btModificaNome.setGeometry(QtCore.QRect(180, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btModificaNome.setFont(font)
        self.btModificaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btModificaNome.setObjectName("btModificaNome")
        self.btEliminaNome = QtWidgets.QPushButton(Dialog)
        self.btEliminaNome.setGeometry(QtCore.QRect(350, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btEliminaNome.setFont(font)
        self.btEliminaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btEliminaNome.setObjectName("btEliminaNome")
        # self.line = QtWidgets.QFrame(Dialog)
        # self.line.setGeometry(QtCore.QRect(0, 460, 521, 16))
        # self.line.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line.setObjectName("line")
#         self.btIndietro = QtWidgets.QPushButton(Dialog)
#         self.btIndietro.setGeometry(QtCore.QRect(10, 480, 51, 51))
#         self.btIndietro.setStyleSheet("\n"
# "image: url(:/icone/Icons/arrow-left.svg);")
#         self.btIndietro.setText("")
#         self.btIndietro.setObjectName("btIndietro")
#         self.btIndietro.clicked.connect(self.btIndietroClicked)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.init_db()
        self.load_data_tabella()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gestione della tabella dei nomi"))
        item = self.tableNomi.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableNomi.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableNomi.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Vegano"))
        item = self.tableNomi.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Piccante"))
        item = self.tableNomi.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Intolleranze"))
        self.btInserisciNome.setText(_translate("Dialog", "Inserisci"))
        self.btModificaNome.setText(_translate("Dialog", "Modifica"))
        self.btEliminaNome.setText(_translate("Dialog", "Elimina"))

    def init_db(self):
        self.db = mysql.connector.connect(
            host="localhost",
            user="root",
            password="alessio",
            database="mydbristorante"
        )


    def load_data_tabella(self):
        self.db.reconnect()
        cur = self.db.cursor()
        query = """select *
                from nomeelemento"""
        cur.execute(query)
        result = cur.fetchall()
        self.tableNomi.setRowCount(0)
        for row_number, row_data in enumerate(result):
            print(row_number)
            self.tableNomi.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                print(f"{data}, {column_number}")
                self.tableNomi.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        self.tableNomi.resizeColumnsToContents()

    def btIndietroClicked(self):
        self.parent.close()



if __name__ == "__main__":
            import sys
            app = QtWidgets.QApplication(sys.argv)
            formGestioneMagazzino = QtWidgets.QDialog()
            ui = (Ui_Dialog())
            ui.setupUi(formGestioneMagazzino)
            formGestioneMagazzino.show()
            sys.exit(app.exec_())


