# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestioneNomi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 540)
        Dialog.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 501, 381))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.btInserisciNome = QtWidgets.QPushButton(Dialog)
        self.btInserisciNome.setGeometry(QtCore.QRect(10, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btInserisciNome.setFont(font)
        self.btInserisciNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btInserisciNome.setObjectName("btInserisciNome")
        self.btModificaNome = QtWidgets.QPushButton(Dialog)
        self.btModificaNome.setGeometry(QtCore.QRect(180, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btModificaNome.setFont(font)
        self.btModificaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btModificaNome.setObjectName("btModificaNome")
        self.btEliminaNome = QtWidgets.QPushButton(Dialog)
        self.btEliminaNome.setGeometry(QtCore.QRect(350, 400, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btEliminaNome.setFont(font)
        self.btEliminaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btEliminaNome.setObjectName("btEliminaNome")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 460, 521, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btIndietro = QtWidgets.QPushButton(Dialog)
        self.btIndietro.setGeometry(QtCore.QRect(10, 480, 51, 51))
        self.btIndietro.setStyleSheet("\n"
"image: url(:/icone/Icons/arrow-left.svg);")
        self.btIndietro.setText("")
        self.btIndietro.setObjectName("btIndietro")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gestione della tabella dei nomi"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Vegano"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Piccante"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Intolleranze"))
        self.btInserisciNome.setText(_translate("Dialog", "Inserisci"))
        self.btModificaNome.setText(_translate("Dialog", "Modifica"))
        self.btEliminaNome.setText(_translate("Dialog", "Elimina"))


if __name__ == "__main__":
            import sys
            app = QtWidgets.QApplication(sys.argv)
            formGestioneNomi = QtWidgets.QDialog()
            ui = (Ui_Dialog())
            ui.setupUi(formGestioneNomi)
            formGestioneNomi.show()
            sys.exit(app.exec_())


