# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestioneNomi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql
import mysql.connector
from PyQt5.QtSql import QSqlQueryModel
from PyQt5.QtWidgets import QTableWidgetItem, QMainWindow, QPushButton, QMessageBox
import Resources.icons
import classi.GestoriDB.GestoreElementiMagazzino as GestoreDBMagazzino
import formAggiungiModificaNomeElemento

class Ui_Dialog(object):
    def chiudiMain(self):
        pass

    def setupUi(self, Dialog):
        self.fGestioneNomi = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 450)
        Dialog.setStyleSheet("background-color: rgb(159, 197, 248);")
        self.tableNomi = QtWidgets.QTableWidget(Dialog)
        self.tableNomi.setGeometry(QtCore.QRect(10, 10, 501, 361))
        self.tableNomi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableNomi.setObjectName("tableNomi")
        self.tableNomi.setColumnCount(5)
        self.tableNomi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNomi.setHorizontalHeaderItem(4, item)
        self.btInserisciNome = QtWidgets.QPushButton(Dialog)
        self.btInserisciNome.setGeometry(QtCore.QRect(10, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btInserisciNome.setFont(font)
        self.btInserisciNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btInserisciNome.setObjectName("btInserisciNome")
        self.btModificaNome = QtWidgets.QPushButton(Dialog)
        self.btModificaNome.setGeometry(QtCore.QRect(180, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btModificaNome.setFont(font)
        self.btModificaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btModificaNome.setObjectName("btModificaNome")
        self.btEliminaNome = QtWidgets.QPushButton(Dialog)
        self.btEliminaNome.setGeometry(QtCore.QRect(350, 380, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.btEliminaNome.setFont(font)
        self.btEliminaNome.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btEliminaNome.setObjectName("btEliminaNome")
        # self.line = QtWidgets.QFrame(Dialog)
        # self.line.setGeometry(QtCore.QRect(0, 460, 521, 16))
        # self.line.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line.setObjectName("line")
#         self.btIndietro = QtWidgets.QPushButton(Dialog)
#         self.btIndietro.setGeometry(QtCore.QRect(10, 480, 51, 51))
#         self.btIndietro.setStyleSheet("\n"
# "image: url(:/icone/Icons/arrow-left.svg);")
#         self.btIndietro.setText("")
#         self.btIndietro.setObjectName("btIndietro")
#         self.btIndietro.clicked.connect(self.btIndietroClicked)
        self.btInserisciNome.clicked.connect(self.btInserisciNomeClicked)
        self.btModificaNome.clicked.connect(self.btModificaNomeClicked)
        self.btEliminaNome.clicked.connect(self.btEliminaNomeClicked)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.load_data_tabella()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Gestione della tabella dei nomi"))
        item = self.tableNomi.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableNomi.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nome"))
        item = self.tableNomi.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Vegano"))
        item = self.tableNomi.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Piccante"))
        item = self.tableNomi.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Intolleranze"))
        self.btInserisciNome.setText(_translate("Dialog", "Inserisci"))
        self.btModificaNome.setText(_translate("Dialog", "Modifica"))
        self.btEliminaNome.setText(_translate("Dialog", "Elimina"))


    def btInserisciNomeClicked(self):
        self.fGestioneNomi.setEnabled(False)
        self.formInserisci = QtWidgets.QDialog()
        self.uiModifica = formAggiungiModificaNomeElemento.Ui_formCU_nomeElemento()
        self.uiModifica.setupUi(self.formInserisci)
        self.formInserisci.exec_()
        self.fGestioneNomi.setEnabled(True)
        self.load_data_tabella()
    def btModificaNomeClicked(self):
        # self.fMagazzino.setEnabled(False)
        # self.formModifica = QtWidgets.QDialog()
        # self.uiModifica = formAggiungiModificaElementoMagazzino.Ui_formCU_elementoMagazzino()
        # self.uiModifica.setupUi(self.formModifica)
        # self.uiModifica.fCUelementoMagazzino.setWindowTitle("Modifica elemento magazzino")
        # self.uiModifica.idToUpdate = int(self.tableMagazzino.item(self.tableMagazzino.currentRow(), 0).text())
        # dataStringa = self.tableMagazzino.item(self.tableMagazzino.currentRow(), 4).text()
        # dataScadenzaDate = datetime.strptime(dataStringa, '%Y-%m-%d').date()
        # self.uiModifica.dateEditScadenza.setDate(dataScadenzaDate)
        # self.uiModifica.numberQuantita.setValue(
        #     float(self.tableMagazzino.item(self.tableMagazzino.currentRow(), 3).text()))
        # PrezzoSenzaEuro = self.tableMagazzino.item(self.tableMagazzino.currentRow(), 2).text().replace("€", "")
        # self.uiModifica.numberPrezzo.setValue(float(PrezzoSenzaEuro))
        # self.uiModifica.txtFornitore.setText(self.tableMagazzino.item(self.tableMagazzino.currentRow(), 5).text())
        # self.formModifica.exec_()
        # self.fMagazzino.setEnabled(True)
        # self.load_data_tabella()
        selectedRow = self.tableNomi.currentRow()
        if selectedRow == -1:
            dlg = QMessageBox()
            dlg.setWindowTitle("Errore")
            dlg.setText("Non hai selezionato nessun elemento!")
            dlg.setStandardButtons(QMessageBox.Ok)
            dlg.setIcon(QMessageBox.Critical)
            dlg.exec()
        else:
            self.fGestioneNomi.setEnabled(False)
            self.formModifica = QtWidgets.QDialog()
            self.uiModifica = formAggiungiModificaNomeElemento.Ui_formCU_nomeElemento()
            self.uiModifica.setupUi(self.formModifica)
            self.uiModifica.idToUpdate = int(self.tableNomi.item(self.tableNomi.currentRow(), 0 ).text())
            print(str(self.tableNomi.item(self.tableNomi.currentRow(), 2).text()))
            if str(self.tableNomi.item(self.tableNomi.currentRow(), 2).text()) == "Si":
                self.uiModifica.checkBoxVegano.setChecked(True)
            else:
                self.uiModifica.checkBoxVegano.setChecked(False)
            if str(self.tableNomi.item(self.tableNomi.currentRow(), 3).text()) == "Si":
                self.uiModifica.checkBoxPiccante.setChecked(True)
            else:
                self.uiModifica.checkBoxPiccante.setChecked(False)
            self.uiModifica.txtNome.setText(self.tableNomi.item(self.tableNomi.currentRow(), 1 ).text())
            self.uiModifica.txtIntolleranze.setText(self.tableNomi.item(self.tableNomi.currentRow(), 4 ).text()) #da modificare qui, di sicuro dopo txtIntolleranze ci va qualcosa per cambiare testo
            self.formModifica.exec_()
            self.fGestioneNomi.setEnabled(True)
            self.load_data_tabella()

    def btEliminaNomeClicked(self):
        selectedRow = self.tableNomi.currentRow()
        if selectedRow == -1:
            dlg = QMessageBox()
            dlg.setWindowTitle("Errore")
            dlg.setText("Non hai selezionato nessun elemento!")
            dlg.setStandardButtons(QMessageBox.Ok)
            dlg.setIcon(QMessageBox.Critical)
            dlg.exec()
        else:
            dlg = QMessageBox()
            dlg.setWindowTitle("Eliminazione elemento magazzino")
            dlg.setText(
                f"Sicuro di voler eliminare il nomeElemento con nome: {self.tableNomi.item(selectedRow, 2).text()}>")
            dlg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
            dlg.setIcon(QMessageBox.Warning)
            button = dlg.exec()
            if button == QMessageBox.Yes:
                query = f"DELETE FROM nomeelemento WHERE id = {self.tableNomi.item(selectedRow, 0).text()}"
                GestoreDBMagazzino.eseguiQuery()
            self.load_data_tabella()

    def load_data_tabella(self):
        result = GestoreDBMagazzino.ottieniNomiElementiGestioneNomi()
        # self.db.reconnect()
        # cur = self.db.cursor()
        # query = """select *
        #         from nomeelemento"""
        # cur.execute(query)
        # result = cur.fetchall()
        self.tableNomi.setRowCount(0)
        for row_number, row_data in enumerate(result):
            print(row_number)
            self.tableNomi.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                print(f"{data}, {column_number}")
                if column_number == 2 or column_number == 3:
                    if data == 0:
                        self.tableNomi.setItem(row_number, column_number, QTableWidgetItem("No"))
                    elif data == 1:
                        self.tableNomi.setItem(row_number, column_number, QTableWidgetItem("Si"))
                else:
                    self.tableNomi.setItem(row_number, column_number, QTableWidgetItem(str(data)))

        self.tableNomi.resizeColumnsToContents()




if __name__ == "__main__":
            import sys
            app = QtWidgets.QApplication(sys.argv)
            formGestioneMagazzino = QtWidgets.QDialog()
            ui = (Ui_Dialog())
            ui.setupUi(formGestioneMagazzino)
            formGestioneMagazzino.show()
            sys.exit(app.exec_())


