# -*- coding: utf-8 -*-
import mysql
# Form implementation generated from reading ui file 'F:\Users\framo\Desktop\ProgettoING-master\form_ui\Aggiungi_Tavolo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from MySQLdb import Error
from PyQt5 import QtCore, QtGui, QtWidgets
from db_connection import get_connection


class Ui_FrameAggiungiTavolo(object):
    def setupUi(self, FrameAggiungiTavolo):
        self.form=FrameAggiungiTavolo
        FrameAggiungiTavolo.setObjectName("FrameAggiungiTavolo")
        FrameAggiungiTavolo.resize(266, 227)
        self.lineEdit = QtWidgets.QLineEdit(FrameAggiungiTavolo)
        self.lineEdit.setGeometry(QtCore.QRect(130, 40, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(FrameAggiungiTavolo)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FrameAggiungiTavolo)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(FrameAggiungiTavolo)
        self.comboBox.setGeometry(QtCore.QRect(130, 90, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btConferma = QtWidgets.QPushButton(FrameAggiungiTavolo)
        self.btConferma.setGeometry(QtCore.QRect(80, 160, 111, 41))
        self.btConferma.setStyleSheet("background-color: rgb(129, 202, 95);")
        self.btConferma.setObjectName("btConferma")
        # Connetti il clic del pulsante "Conferma" alla funzione btConfermaClicked
        self.btConferma.clicked.connect(self.btConfermaClicked)

        self.retranslateUi(FrameAggiungiTavolo)
        QtCore.QMetaObject.connectSlotsByName(FrameAggiungiTavolo)

    def retranslateUi(self, FrameAggiungiTavolo):
        _translate = QtCore.QCoreApplication.translate
        FrameAggiungiTavolo.setWindowTitle(_translate("FrameAggiungiTavolo", "Aggiungi Tavolo"))
        self.lineEdit.setInputMask(_translate("FrameAggiungiTavolo", "000"))
        self.label.setText(_translate("FrameAggiungiTavolo", "Numero:"))
        self.label_2.setText(_translate("FrameAggiungiTavolo", "Sala:"))
        self.comboBox.setItemText(0, _translate("FrameAggiungiTavolo", "Pizzeria"))
        self.comboBox.setItemText(1, _translate("FrameAggiungiTavolo", "Principale"))
        self.comboBox.setItemText(2, _translate("FrameAggiungiTavolo", "Prive"))
        self.comboBox.setItemText(3, _translate("FrameAggiungiTavolo", "Open Space"))
        self.comboBox.setItemText(4, _translate("FrameAggiungiTavolo", "Saletta"))
        self.btConferma.setText(_translate("FrameAggiungiTavolo", "Conferma"))

    def btConfermaClicked(self):
        # Ottieni il numero del tavolo dalla QLineEdit e rimuovi eventuali spazi all'inizio o alla fine
        numero_tavolo = self.lineEdit.text().strip()

        # Verifica se il numero del tavolo è vuoto dopo aver rimosso gli spazi
        if not numero_tavolo:
            QtWidgets.QMessageBox.warning(None, "Errore", "Inserisci un numero per il tavolo.")
            return

        # Ottieni la sala selezionata dalla QComboBox
        sala = self.comboBox.currentText().lower()  # Converte la sala in minuscolo

        # Stato predefinito del tavolo
        stato = "libero"

        # Ora puoi aggiungere questi dati al database
        try:
            myconn = get_connection()
            cursor = myconn.cursor()

            # Esecuzione della query per inserire il nuovo tavolo nel database
            query = "INSERT INTO tavolo (numero, sala, stato) VALUES (%s, %s, %s)"
            cursor.execute(query, (numero_tavolo, sala, stato))

            # Conferma l'esecuzione della query
            myconn.commit()

            # Mostra un messaggio di successo
            QtWidgets.QMessageBox.information(None, "Successo", "Tavolo aggiunto con successo al database.")

        except Error as e:
            print(f"Errore durante l'accesso al database: {e}")

            # Mostra un messaggio di errore
            QtWidgets.QMessageBox.critical(None, "Errore", f"Errore durante l'aggiunta del tavolo al database: {e}")

        finally:
            if myconn:
                myconn.close()
            self.form.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FrameAggiungiTavolo = QtWidgets.QDialog()
    ui = Ui_FrameAggiungiTavolo()
    ui.setupUi(FrameAggiungiTavolo)
    FrameAggiungiTavolo.show()
    sys.exit(app.exec_())
