# -*- coding: utf-8 -*-

import mysql
import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
from db_connection import get_connection
from PyQt5.QtWidgets import QMessageBox
from mysql.connector import Error
import Metodi_Gestione_Tavoli
from datetime import datetime, timedelta
from form_Cameriere import formTavoli

# Form implementation generated from reading ui file 'C:\Users\framo\PycharmProjects\test\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_formLogin(object):
    def setupUi(self, formLogin):
        formLogin.setObjectName("formLogin")
        formLogin.resize(421, 294)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        formLogin.setFont(font)
        formLogin.setStyleSheet("background-color:rgb(159, 197, 248)")
        self.lblLogin = QtWidgets.QLabel(formLogin)
        self.lblLogin.setGeometry(QtCore.QRect(180, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.label = QtWidgets.QLabel(formLogin)
        self.label.setGeometry(QtCore.QRect(140, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("F:/Users/framo/Desktop/Foto ing del SW/impronta-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(formLogin)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 291, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(formLogin)
        self.label_3.setGeometry(QtCore.QRect(110, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(formLogin)
        self.label_4.setGeometry(QtCore.QRect(110, 160, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btAccedi = QtWidgets.QPushButton(formLogin)
        self.btAccedi.setGeometry(QtCore.QRect(150, 230, 121, 41))
        self.btAccedi.setStyleSheet("background-color: rgb(245, 243, 201);")
        self.btAccedi.setCheckable(False)
        self.btAccedi.setObjectName("btAccedi")
        self.btAccedi.clicked.connect(self.btAccediClicked)
        self.tbpassword = QtWidgets.QLineEdit(formLogin)
        self.tbpassword.setGeometry(QtCore.QRect(110, 180, 191, 31))
        self.tbpassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tbpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tbpassword.setObjectName("tbpassword")
        self.tbUsername = QtWidgets.QLineEdit(formLogin)
        self.tbUsername.setGeometry(QtCore.QRect(110, 120, 191, 31))
        self.tbUsername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tbUsername.setObjectName("tbUsername")
        formLogin.setTabOrder(self.tbUsername, self.tbpassword)
        formLogin.setTabOrder(self.tbpassword, self.btAccedi)
        self.retranslateUi(formLogin)
        QtCore.QMetaObject.connectSlotsByName(formLogin)

    
    def btAccediClicked(self):
        Metodi_Gestione_Tavoli.aggiorna_stato_tavoli()
        username = self.tbUsername.text()
        password = self.tbpassword.text()
        print("Username: " + username)
        print("Password: " + password)
        print("Controllo account:")
        if username == "" or password == "":
            QMessageBox.warning(None, "Accesso negato", "Username o password non validi!")
        else:
            try:
                # Connessione al db
                myconn = get_connection()
                cursor = myconn.cursor()

                # Esecuzione della query per cercare l'account
                query = "SELECT * FROM account WHERE username = %s AND pwd = %s"
                cursor.execute(query, (username, password))
                account = cursor.fetchone()

                if account:
                    role = account[2]
                    QMessageBox.information(None, "Accesso consentito", "Accesso consentito! Benvenuto! Ruolo: "+role)
                    # Apertura della form corretta in base al ruolo
                    if role == "cameriere":
                        from form_Cameriere import formTavoli
                        self.formTavoli = QtWidgets.QDialog()
                        self.uiTavoli = formTavoli.Ui_FormCameriere()
                        self.uiTavoli.setupUi(self.formTavoli)
                        self.formTavoli.show()
                    elif role == "admin":
                        from form_Amministratore import menuAmministratore
                        self.formAdmin = QtWidgets.QDialog()
                        self.uiAdmin = menuAmministratore.Ui_formAmministratore()
                        self.uiAdmin.setupUi(self.formAdmin)
                        self.formAdmin.show()
                    elif role == "cuoco":
                        from form_Cuoco import Accesso_Cuoco
                        self.Accesso_Cuoco = QtWidgets.QDialog()
                        self.uiCuoco = Accesso_Cuoco.Ui_Form_Accesso_Cuoco()
                        self.uiCuoco.setupUi(self.Accesso_Cuoco)
                        self.Accesso_Cuoco.show()
                else:
                    QMessageBox.warning(None, "Accesso negato", "Username o password non validi!")

            except Error as e:
                print(f"Errore durante l'accesso al database: {e}")

            finally:
                # Chiusura della connessione
                if myconn:
                    myconn.close()

    def retranslateUi(self, formLogin):
        _translate = QtCore.QCoreApplication.translate
        formLogin.setWindowTitle(_translate("formLogin", "Login"))
        self.lblLogin.setText(_translate("formLogin", "Login"))
        self.label_2.setText(_translate("formLogin", "Inserire le credenziali per accedere al sistema"))
        self.label_3.setText(_translate("formLogin", "Username"))
        self.label_4.setText(_translate("formLogin", "Password"))
        self.btAccedi.setText(_translate("formLogin", "Accedi"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formLogin = QtWidgets.QDialog()
    ui = Ui_formLogin()
    ui.setupUi(formLogin)
    formLogin.show()
    sys.exit(app.exec_())
